/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagement;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;

//import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.util.Calendar;
//import java.util.GregorianCalendar;


/**
 *
 * @author Thiline Tissera
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private String currentDate;
    private String currenTime;
    
    public Home() {
        initComponents();
        showTime();
        showDate();
        
       HomeDesktop.removeAll();
       TimeTable tt = new TimeTable();
       HomeDesktop.add(tt).setVisible(true);
       tt.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
       
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomeDesktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnStudents = new javax.swing.JButton();
        btnSubjects = new javax.swing.JButton();
        btnLecturers = new javax.swing.JButton();
        btnTags = new javax.swing.JButton();
        btnWorkingD = new javax.swing.JButton();
        BtnLocation = new javax.swing.JButton();
        BtnStat = new javax.swing.JButton();
        btnTimetble = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnsessions = new javax.swing.JButton();
        btn_Unavailable_Location = new javax.swing.JButton();
        btn_rooms = new javax.swing.JButton();
        btn_sSession = new javax.swing.JButton();
        date_L = new javax.swing.JLabel();
        Time_L1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout HomeDesktopLayout = new javax.swing.GroupLayout(HomeDesktop);
        HomeDesktop.setLayout(HomeDesktopLayout);
        HomeDesktopLayout.setHorizontalGroup(
            HomeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HomeDesktopLayout.setVerticalGroup(
            HomeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        btnStudents.setBackground(new java.awt.Color(51, 51, 51));
        btnStudents.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnStudents.setText("Students");
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });

        btnSubjects.setBackground(new java.awt.Color(51, 51, 51));
        btnSubjects.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSubjects.setForeground(new java.awt.Color(255, 255, 255));
        btnSubjects.setText("Subjects");
        btnSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectsActionPerformed(evt);
            }
        });

        btnLecturers.setBackground(new java.awt.Color(51, 51, 51));
        btnLecturers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLecturers.setForeground(new java.awt.Color(255, 255, 255));
        btnLecturers.setText("Lecturers");
        btnLecturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturersActionPerformed(evt);
            }
        });

        btnTags.setBackground(new java.awt.Color(51, 51, 51));
        btnTags.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTags.setForeground(new java.awt.Color(255, 255, 255));
        btnTags.setText("Tags");
        btnTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagsActionPerformed(evt);
            }
        });

        btnWorkingD.setBackground(new java.awt.Color(51, 51, 51));
        btnWorkingD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnWorkingD.setForeground(new java.awt.Color(255, 255, 255));
        btnWorkingD.setText("Working Time");
        btnWorkingD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkingDActionPerformed(evt);
            }
        });

        BtnLocation.setBackground(new java.awt.Color(51, 51, 51));
        BtnLocation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnLocation.setForeground(new java.awt.Color(255, 255, 255));
        BtnLocation.setText("Location");
        BtnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLocationActionPerformed(evt);
            }
        });

        BtnStat.setBackground(new java.awt.Color(51, 51, 51));
        BtnStat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnStat.setForeground(new java.awt.Color(255, 255, 255));
        BtnStat.setText("Statistics");
        BtnStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStatActionPerformed(evt);
            }
        });

        btnTimetble.setBackground(new java.awt.Color(51, 51, 51));
        btnTimetble.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTimetble.setForeground(new java.awt.Color(255, 255, 255));
        btnTimetble.setText("Time Tables");
        btnTimetble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimetbleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWorkingD, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubjects, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnStat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLecturers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimetble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStudents, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnLecturers, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTags, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnWorkingD, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BtnLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BtnStat, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTimetble, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        btnsessions.setBackground(new java.awt.Color(51, 51, 51));
        btnsessions.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsessions.setForeground(new java.awt.Color(255, 255, 255));
        btnsessions.setText("Sessions");
        btnsessions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsessionsActionPerformed(evt);
            }
        });

        btn_Unavailable_Location.setBackground(new java.awt.Color(51, 51, 51));
        btn_Unavailable_Location.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_Unavailable_Location.setForeground(new java.awt.Color(255, 255, 255));
        btn_Unavailable_Location.setText("Unavailable Location");
        btn_Unavailable_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Unavailable_LocationActionPerformed(evt);
            }
        });

        btn_rooms.setBackground(new java.awt.Color(51, 51, 51));
        btn_rooms.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_rooms.setForeground(new java.awt.Color(255, 255, 255));
        btn_rooms.setText("Rooms");
        btn_rooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_roomsActionPerformed(evt);
            }
        });

        btn_sSession.setBackground(new java.awt.Color(51, 51, 51));
        btn_sSession.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_sSession.setForeground(new java.awt.Color(255, 255, 255));
        btn_sSession.setText("Special Sessions");
        btn_sSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnsessions, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btn_sSession)
                .addGap(44, 44, 44)
                .addComponent(btn_Unavailable_Location)
                .addGap(39, 39, 39)
                .addComponent(btn_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_rooms, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btn_sSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsessions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Unavailable_Location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        date_L.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Time_L1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)
                        .addComponent(Time_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_L, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HomeDesktop))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Time_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date_L, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HomeDesktop)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void showDate() 
    {

        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        currentDate = s.format(d);
        date_L.setText(currentDate);
    }

    void showTime()
    {

        new Timer(0, new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent ae) 
            {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                currenTime = s.format(d);
                Time_L1.setText(currenTime);
            }
        }).start();
    }

    
    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
       HomeDesktop.removeAll();
       Student std = new Student();
       HomeDesktop.add(std).setVisible(true);
       std.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnLecturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturersActionPerformed
       HomeDesktop.removeAll();
       Lecturer lc = new Lecturer();
       HomeDesktop.add(lc).setVisible(true);
       lc.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btnLecturersActionPerformed

    private void btnSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectsActionPerformed
       HomeDesktop.removeAll();
       Subjects sb = new Subjects();
       HomeDesktop.add(sb).setVisible(true);
       sb.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btnSubjectsActionPerformed

    private void btnTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagsActionPerformed
       HomeDesktop.removeAll();
       Tags tg = new Tags();
       HomeDesktop.add(tg).setVisible(true);
       tg.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btnTagsActionPerformed

    private void btnWorkingDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkingDActionPerformed
       HomeDesktop.removeAll();
       WorkingTime wt = new WorkingTime();
       HomeDesktop.add(wt).setVisible(true);
       wt.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btnWorkingDActionPerformed

    private void BtnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLocationActionPerformed
 
       HomeDesktop.removeAll();
       locaManage lm = new locaManage();
       HomeDesktop.add(lm).setVisible(true);
       lm.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_BtnLocationActionPerformed

    private void BtnStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStatActionPerformed
       
       HomeDesktop.removeAll();
       Statistic st = new Statistic();
       HomeDesktop.add(st).setVisible(true);
       st.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight()); 

       
    }//GEN-LAST:event_BtnStatActionPerformed

    private void btnTimetbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimetbleActionPerformed
       HomeDesktop.removeAll();
       TimeTable tt  = new TimeTable();
       HomeDesktop.add(tt).setVisible(true);
       tt.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btnTimetbleActionPerformed

    private void btnsessionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsessionsActionPerformed
        
       HomeDesktop.removeAll();
       Manage_Sessions se = new Manage_Sessions();
       HomeDesktop.add(se).setVisible(true);
       se.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btnsessionsActionPerformed

    private void btn_sSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sSessionActionPerformed
       HomeDesktop.removeAll();
       SpecialSession ss = new SpecialSession();
       HomeDesktop.add(ss).setVisible(true);
       ss.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btn_sSessionActionPerformed

    private void btn_roomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomsActionPerformed
       HomeDesktop.removeAll();
       sessionRooms sr = new sessionRooms();
       HomeDesktop.add(sr).setVisible(true);
       sr.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btn_roomsActionPerformed

    private void btn_Unavailable_LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Unavailable_LocationActionPerformed
       HomeDesktop.removeAll();
       Sessions ss = new Sessions();
       HomeDesktop.add(ss).setVisible(true);
       ss.setSize(HomeDesktop.getWidth(), HomeDesktop.getHeight());
    }//GEN-LAST:event_btn_Unavailable_LocationActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              /*  if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;*/
              UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel"); //("com.jtattoo.plaf.noire.NoireLookAndFeel");
                }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }  // java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLocation;
    private javax.swing.JButton BtnStat;
    public static javax.swing.JDesktopPane HomeDesktop;
    private javax.swing.JLabel Time_L1;
    private javax.swing.JButton btnLecturers;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnSubjects;
    private javax.swing.JButton btnTags;
    private javax.swing.JButton btnTimetble;
    private javax.swing.JButton btnWorkingD;
    private javax.swing.JButton btn_Unavailable_Location;
    private javax.swing.JButton btn_rooms;
    private javax.swing.JButton btn_sSession;
    private javax.swing.JButton btnsessions;
    private javax.swing.JLabel date_L;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
