/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagement;

import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import static timetablemanagement.Home.HomeDesktop;


/**
 *
 * @author Dulani
 */
public class LecUnavailable extends javax.swing.JPanel {

    /**
     * Creates new form LecUnavailable
     */
    public LecUnavailable() {
        initComponents();
        LoadTable();
        lecsDetails();
        TimeValidate();
    }
public void LoadTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        try {
              
                ResultSet rs = DataBase.getData("Select id,lecName,lGrp,lsbgrp,lssID,Ldate,lFrom,lTo from lecun");
                
                while (rs.next())
                {

                    Vector v = new Vector();
                   
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));  
                    v.add(rs.getString(3));  
                    v.add(rs.getString(4));  
                    v.add(rs.getString(5));
                    v.add(rs.getString(6));  
                    v.add(rs.getString(7));  
                    v.add(rs.getString(8));
                    dtm.addRow(v);

                }

            } catch (Exception e) 
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lnmCb = new javax.swing.JComboBox<>();
        SsIDCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        GrpCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        SubGrpCB = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DateCB = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        StimeCb = new javax.swing.JComboBox<>();
        EtimeCb = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1076, 818));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Select Lecturer");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Select Session ID");

        SsIDCB.setPreferredSize(new java.awt.Dimension(60, 25));
        SsIDCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SsIDCBMouseClicked(evt);
            }
        });
        SsIDCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SsIDCBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Select Group");

        GrpCB.setPreferredSize(new java.awt.Dimension(60, 25));
        GrpCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrpCBMouseClicked(evt);
            }
        });
        GrpCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrpCBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Select Sub Group");

        SubGrpCB.setPreferredSize(new java.awt.Dimension(60, 25));
        SubGrpCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubGrpCBMouseClicked(evt);
            }
        });
        SubGrpCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubGrpCBActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Date");

        DateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", " " }));
        DateCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateCBActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Time(24hr)");

        StimeCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "08.00", "08.30", "09.00", "09.30", "10.00", "10.30", "11.00", "11.30", "12.00", "12.30", "13.00", "13.30", "14.00", "14.30", "15.00", "15.30", "16.00", "16.30", "17.00", "17.30", " " }));
        StimeCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StimeCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(GrpCB, 0, 172, Short.MAX_VALUE)
                                .addComponent(SubGrpCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(lnmCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(SsIDCB, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(104, 104, 104)))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(83, 83, 83)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(131, 131, 131))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(StimeCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addComponent(EtimeCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(155, 155, 155))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnmCb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SsIDCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrpCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubGrpCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StimeCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtimeCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "lecName ", "lGrp", "lsbgrp", "lssID", "Ldate", "lFrom", "​lTo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubGrpCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubGrpCBMouseClicked
//        try
//        {
//
//            ResultSet rs = DataBase.getData("SELECT * FROM student ");
//            while (rs.next())
//            {
//                String sgID = rs.getString("subGrpID");
//                SubGrpCB.addItem(sgID);
//
//            }
//
//        }
//        catch (Exception e)
//        {
//
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_SubGrpCBMouseClicked

    private void SsIDCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SsIDCBMouseClicked
//        try
//        {
//
//            ResultSet rs = DataBase.getData("SELECT * FROM session ");
//            while (rs.next())
//            {
//                String ssID = rs.getString("SessionID");
//                SsIDCB.addItem(ssID);
//
//            }
//
//        }
//        catch (Exception e)
//        {
//
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_SsIDCBMouseClicked

    private void DateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateCBActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
        try {
            // jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            ResultSet rs = DataBase.getData("SELECT Lecturer_name FROM lecturer ");
            while (rs.next())
            {
                lnmCb.setSelectedItem(rs);
                lnmCb.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            }
            
            
            
            GrpCB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            SubGrpCB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            SsIDCB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            DateCB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            StimeCb.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            EtimeCb.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        } catch (Exception ex) {
            Logger.getLogger(LecUnavailable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        HomeDesktop.removeAll();
        SpecialSession ss = new SpecialSession();
        HomeDesktop.add(ss).setVisible(true);
        ss.setSize(HomeDesktop.getWidth(),HomeDesktop.getHeight());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GrpCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrpCBActionPerformed
        try
        {

            ResultSet rs = DataBase.getData("SELECT * FROM student ");
            while (rs.next())
            {
                String gID = rs.getString("GrpID");
                GrpCB.addItem(gID);

            }

        }
        catch (Exception e)
        {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_GrpCBActionPerformed

    private void GrpCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrpCBMouseClicked
//        try
//        {
//
//            ResultSet rs = DataBase.getData("SELECT * FROM student ");
//            while (rs.next())
//            {
//                String gID = rs.getString("GrpID");
//                GrpCB.addItem(gID);
//
//            }
//
//        }
//        catch (Exception e)
//        {
//
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_GrpCBMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        String ID = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
 
        if (row != -1) 
        {
        
            int confirm = JOptionPane.showConfirmDialog(null, "Do you want to delete?", "Delete", JOptionPane.YES_NO_OPTION); 
            if (confirm == 0) 
            {
                try
                {
                  DataBase.setData("DELETE FROM lecun WHERE id = '"+ID+"'");
                  JOptionPane.showMessageDialog(null, "Successfully Deleted");

                }
                catch (Exception e)
                {
                          JOptionPane.showMessageDialog(null, "Failed" + e);
                }
              LoadTable();
            
            }
        }
        else
        {
             JOptionPane.showMessageDialog(null, "Please Select a Row to Delete");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        String lecture ="";
        String group ="";
        String subgroup ="";
        String ssID ="";
        String date ="";
        String tFrom ="";
        String tTo ="";
      String Id=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
       lecture = lnmCb.getSelectedItem().toString();
        group = GrpCB.getSelectedItem().toString();
        subgroup = SubGrpCB.getSelectedItem().toString(); 
        ssID = SsIDCB.getSelectedItem().toString();
        date = DateCB.getSelectedItem().toString();
        tFrom = StimeCb.getSelectedItem().toString(); 
        tTo = EtimeCb.getSelectedItem().toString(); 
        
       
       try
                {DataBase.setData("UPDATE lecun set lecName = '"+lecture+"', lGrp = '"+group+"', lsbgrp = '"+subgroup+"', lssID = '"+ssID+"', Ldate = '"+date+"', lFrom = '"+tFrom+"', lTo = '"+tTo+"' where  id= '"+Id+"' ");
                  JOptionPane.showMessageDialog(null, "Details Successfully Updated");
                  jTable1.removeAll();
                  
}
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Failed" + e);
                }
        LoadTable();
       //refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void StimeCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StimeCbActionPerformed
        TimeValidate();
    }//GEN-LAST:event_StimeCbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoadTable();
        //refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SubGrpCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubGrpCBActionPerformed
     try
        {

            ResultSet rs = DataBase.getData("SELECT * FROM student ");
            while (rs.next())
            {
                String sgID = rs.getString("subGrpID");
                SubGrpCB.addItem(sgID);

            }

        }
        catch (Exception e)
        {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SubGrpCBActionPerformed

    private void SsIDCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SsIDCBActionPerformed
        try
        {

            ResultSet rs = DataBase.getData("SELECT * FROM session ");
            while (rs.next())
            {
                String ssID = rs.getString("SessionID");
                SsIDCB.addItem(ssID);

            }

        }
        catch (Exception e)
        {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SsIDCBActionPerformed

    public void refresh()
    {
         lnmCb.removeAllItems();
        lnmCb.addItem("Select");
        
        GrpCB.removeAllItems();
        GrpCB.addItem("Select");
        
        SubGrpCB.removeAllItems();
        SubGrpCB.addItem("Select");
        
        SsIDCB.removeAllItems();
        SsIDCB.addItem("Select");
    }

private void lecsDetails(){
       
        lnmCb.removeAllItems();
        lnmCb.addItem("Select");
        
        GrpCB.removeAllItems();
        GrpCB.addItem("Select");
        
        SubGrpCB.removeAllItems();
        SubGrpCB.addItem("Select");
        
        SsIDCB.removeAllItems();
        SsIDCB.addItem("Select");
       
       try{
          
            ResultSet rs = DataBase.getData("SELECT l1name, SessionID  FROM session ");
             while(rs.next())
             {
               String name = rs.getString("l1name");
               String ssid =rs.getString("SessionID");
               
               lnmCb.addItem(name);
               SsIDCB.addItem(ssid);
              
            }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       
         String grp = "";
         String subgp ="";
            try{
          
            ResultSet rs = DataBase.getData("SELECT GrpID,subGrpID FROM student");
             while(rs.next())
             {
              
               grp =rs.getString("GrpID");
               subgp = rs.getString("subGrpID");

               GrpCB.addItem(grp);
               SubGrpCB.addItem(subgp);

            }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
         }
private void TimeValidate(){  
          
       if(StimeCb.getSelectedItem().equals("08.00")){
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("08.30");
            EtimeCb.addItem("09.00");
            EtimeCb.addItem("09.30");
            EtimeCb.addItem("10.00");
            EtimeCb.addItem("10.30");
            EtimeCb.addItem("11.00");
            EtimeCb.addItem("11.30");
            EtimeCb.addItem("12.00");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }
       else if(StimeCb.getSelectedItem().equals("08.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("09.00");
            EtimeCb.addItem("09.30");
            EtimeCb.addItem("10.00");
            EtimeCb.addItem("10.30");
            EtimeCb.addItem("11.00");
            EtimeCb.addItem("11.30");
            EtimeCb.addItem("12.00");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("09.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("09.30");
            EtimeCb.addItem("10.00");
            EtimeCb.addItem("10.30");
            EtimeCb.addItem("11.00");
            EtimeCb.addItem("11.30");
            EtimeCb.addItem("12.00");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");   
            
         }else if(StimeCb.getSelectedItem().equals("09.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("10.00");
            EtimeCb.addItem("10.30");
            EtimeCb.addItem("11.00");
            EtimeCb.addItem("11.30");
            EtimeCb.addItem("12.00");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("10.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("10.30");
            EtimeCb.addItem("11.00");
            EtimeCb.addItem("11.30");
            EtimeCb.addItem("12.00");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("10.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("11.00");
            EtimeCb.addItem("11.30");
            EtimeCb.addItem("12.00");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("11.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("11.30");
            EtimeCb.addItem("12.00");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("11.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("12.00");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("12.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("12.30");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");   
            
         }else if(StimeCb.getSelectedItem().equals("12.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("13.00");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("13.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("13.30");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("13.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("14.00");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("14.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("14.30");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("14.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("15.00");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("15.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("15.30");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("15.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("16.00");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("16.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("16.30");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30"); 
            
         }else if(StimeCb.getSelectedItem().equals("16.30")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("17.00");
            EtimeCb.addItem("17.30");  
            
         }else if(StimeCb.getSelectedItem().equals("17.00")){
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
            EtimeCb.addItem("17.30");   
            
         }else{
             
            EtimeCb.removeAllItems();
            EtimeCb.addItem("Select");
         
         }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DateCB;
    private javax.swing.JComboBox<String> EtimeCb;
    private javax.swing.JComboBox<String> GrpCB;
    private javax.swing.JComboBox<String> SsIDCB;
    private javax.swing.JComboBox<String> StimeCb;
    private javax.swing.JComboBox<String> SubGrpCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> lnmCb;
    // End of variables declaration//GEN-END:variables
}
