/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagement;

import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import static timetablemanagement.Home.HomeDesktop;


/**
 *
 * @author Dulani
 */
public class LecUnavailable extends javax.swing.JPanel {

    /**
     * Creates new form LecUnavailable
     */
    public LecUnavailable() {
        initComponents();
        LoadTable();
        lecsDetails();
        TimeValidate();
    }
public void LoadTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        
        try {
              
                ResultSet rs = DataBase.getData("Select id,lecName,lGrp,lsbgrp,lssID,Ldate,lFrom,lTo from lecun");
                
                while (rs.next())
                {

                    Vector v = new Vector();
                   
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));  
                    v.add(rs.getString(3));  
                    v.add(rs.getString(4));  
                    v.add(rs.getString(5));
                    v.add(rs.getString(6));  
                    v.add(rs.getString(7));
                    v.add(rs.getString(8));
                    dtm.addRow(v);

                }

            } catch (Exception e) 
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lnmUpCb = new javax.swing.JComboBox<>();
        SsIDUpCB = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        GrpUpCB = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        SubGrpUpCB = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DateUpCB = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        StimeUpCb = new javax.swing.JComboBox<>();
        EtimeUpCb = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1076, 818));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Select Lecturer");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Select Session ID");

        lnmUpCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        lnmUpCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnmUpCbActionPerformed(evt);
            }
        });

        SsIDUpCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        SsIDUpCB.setPreferredSize(new java.awt.Dimension(60, 25));
        SsIDUpCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SsIDUpCBMouseClicked(evt);
            }
        });
        SsIDUpCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SsIDUpCBActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Select Group");

        GrpUpCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        GrpUpCB.setPreferredSize(new java.awt.Dimension(60, 25));
        GrpUpCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrpUpCBMouseClicked(evt);
            }
        });
        GrpUpCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrpUpCBActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Select Sub Group");

        SubGrpUpCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        SubGrpUpCB.setPreferredSize(new java.awt.Dimension(60, 25));
        SubGrpUpCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubGrpUpCBMouseClicked(evt);
            }
        });
        SubGrpUpCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubGrpUpCBActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Date");

        DateUpCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", " " }));
        DateUpCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateUpCBActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Time(24hr)");

        StimeUpCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "08.00", "08.30", "09.00", "09.30", "10.00", "10.30", "11.00", "11.30", "12.00", "12.30", "13.00", "13.30", "14.00", "14.30", "15.00", "15.30", "16.00", "16.30", "17.00", "17.30", " " }));
        StimeUpCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StimeUpCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SsIDUpCB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(GrpUpCB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(lnmUpCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SubGrpUpCB, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(104, 104, 104)))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(83, 83, 83)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(131, 131, 131))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DateUpCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(StimeUpCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addComponent(EtimeUpCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(155, 155, 155))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnmUpCb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GrpUpCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubGrpUpCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SsIDUpCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateUpCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StimeUpCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtimeUpCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "lecName ", "lGrp", "lsbgrp", "lssID", "Ldate", "lFrom", "​lTo"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SubGrpUpCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubGrpUpCBMouseClicked

    }//GEN-LAST:event_SubGrpUpCBMouseClicked

    private void SsIDUpCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SsIDUpCBMouseClicked

    }//GEN-LAST:event_SsIDUpCBMouseClicked

    private void DateUpCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateUpCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateUpCBActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      SubGrpUpCB.removeAllItems();
//      lecsDetails();
        try
        {
           
           String gp=jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
            ResultSet rs = DataBase.getData("SELECT DISTINCT subGrpID FROM student WHERE  GrpID = '"+gp+"'");
            while (rs.next())
            {
                String sgID = rs.getString("subGrpID");
                SubGrpUpCB.addItem(sgID);

            }

        }
         catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
     
       try {
            
            lnmUpCb.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
             GrpUpCB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            SubGrpUpCB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
           SsIDUpCB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            DateUpCB.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            StimeUpCb.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            EtimeUpCb.setSelectedItem(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        } 
        
        catch (Exception ex) {
            Logger.getLogger(LecUnavailable.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        HomeDesktop.removeAll();
        SpecialSession ss = new SpecialSession();
        HomeDesktop.add(ss).setVisible(true);
        ss.setSize(HomeDesktop.getWidth(),HomeDesktop.getHeight());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GrpUpCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrpUpCBActionPerformed
        SubGrpUpCB.removeAllItems();
        SubGrpUpCB.addItem("Select");
        try
        {
           
           String gp=GrpUpCB.getSelectedItem().toString();
            ResultSet rs = DataBase.getData("SELECT DISTINCT subGrpID FROM student WHERE  GrpID = '"+gp+"'");
            while (rs.next())
            {
                String sgID = rs.getString("subGrpID");
                SubGrpUpCB.addItem(sgID);

            }

        }
        catch (Exception e)
        {

            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_GrpUpCBActionPerformed

    private void GrpUpCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrpUpCBMouseClicked

    }//GEN-LAST:event_GrpUpCBMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String ID = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        if  (row != -1)
        {
            int confirm = JOptionPane.showConfirmDialog(null, "Do you want to delete?", "Delete", JOptionPane.YES_NO_OPTION); 
            if (confirm == 0) 
            {
                try
                {
                  DataBase.setData("DELETE FROM lecun WHERE id = '"+ID+"'");
                  JOptionPane.showMessageDialog(null, "Successfully Deleted");

                }
                catch (Exception e)
                {
                          JOptionPane.showMessageDialog(null, "Failed" + e);
                }
              LoadTable();
            
            }
            else
            {
             JOptionPane.showMessageDialog(null, "Please Select a Row to Delete");
        }
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        String lecture ="";
        String group ="";
        String subgroup ="";
        String ssID ="";
        String date ="";
        String tFrom ="";
        String tTo ="";
      String Id=jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
       lecture = lnmUpCb.getSelectedItem().toString();
        group = GrpUpCB.getSelectedItem().toString();
        subgroup = SubGrpUpCB.getSelectedItem().toString(); 
        ssID = SsIDUpCB.getSelectedItem().toString();
        date = DateUpCB.getSelectedItem().toString();
        tFrom = StimeUpCb.getSelectedItem().toString(); 
        tTo = EtimeUpCb.getSelectedItem().toString(); 
        if(lecture == "Select")
        {
            JOptionPane.showMessageDialog(null, "Select Lecture");
        }
        else if(group == "Select")
        {
            JOptionPane.showMessageDialog(null, "Select Group");
        }
        else if(subgroup == "Select")
        {
            JOptionPane.showMessageDialog(null, "Select Sub Group");
        }
        else if(ssID == "Select")
        {
            JOptionPane.showMessageDialog(null, "Select Session ID");
        }
        else if(date == "Select")
        {
            JOptionPane.showMessageDialog(null, "Select Date");
        }
        else if(tFrom == "Select")
        {
            JOptionPane.showMessageDialog(null, "Enter Unavailable time");
        }
        else if(tTo == "Select")
        {
            JOptionPane.showMessageDialog(null, "Enter Unavailable time");
        }
        else{
       try
                {DataBase.setData("UPDATE lecun set lecName = '"+lecture+"', lGrp = '"+group+"', lsbgrp = '"+subgroup+"', lssID = '"+ssID+"', Ldate = '"+date+"', lFrom = '"+tFrom+"', lTo = '"+tTo+"' where  id= '"+Id+"' ");
                  JOptionPane.showMessageDialog(null, "Details Successfully Updated");
                  jTable1.removeAll();
                  
}
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, "Failed" + e);
                }
        LoadTable();
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void StimeUpCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StimeUpCbActionPerformed
        TimeValidate();
    }//GEN-LAST:event_StimeUpCbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SubGrpUpCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubGrpUpCBActionPerformed

    }//GEN-LAST:event_SubGrpUpCBActionPerformed

    private void SsIDUpCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SsIDUpCBActionPerformed

    }//GEN-LAST:event_SsIDUpCBActionPerformed

    private void lnmUpCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnmUpCbActionPerformed
      
    }//GEN-LAST:event_lnmUpCbActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered
  
public void Clear()
    {
        
        lnmUpCb.setSelectedItem("Select");
        GrpUpCB.setSelectedItem("Select");
        SubGrpUpCB.setSelectedItem("Select");
        SsIDUpCB.setSelectedItem("Select");
        DateUpCB.setSelectedItem("Select");
        StimeUpCb.setSelectedItem("Select");
       EtimeUpCb.setSelectedItem("Select");
       
    }
private void lecsDetails(){
    
    String gp = "";
        try
        {
            ResultSet rs = DataBase.getData("SELECT * FROM lecturer ");
            while (rs.next())
            {
                String LecName = rs.getString("Lecturer_name");
                lnmUpCb.addItem(LecName);
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        //-----------------------------------------------------------------------
        try
        {

            ResultSet rs = DataBase.getData("SELECT DISTINCT GrpID FROM student");
            while (rs.next())
            {
                String gID = rs.getString("GrpID");
                GrpUpCB.addItem(gID);

            }
            gp=GrpUpCB.getSelectedItem().toString();
            System.out.println("GP :" +  gp);
        }
        catch (Exception e)
        {

            JOptionPane.showMessageDialog(null, e);
        }
        
        //-----------------------------------------------------------------------
        
          try
        {

            ResultSet rs = DataBase.getData("SELECT DISTINCT * FROM session ");
            while (rs.next())
            {
                String ssID = rs.getString("SessionID");
                SsIDUpCB.addItem(ssID);

            }
            
        }
        catch (Exception e)
        {

            JOptionPane.showMessageDialog(null, e);
        }
  
         }
private void TimeValidate(){  
          
       if(StimeUpCb.getSelectedItem().equals("08.00")){
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("08.30");
            EtimeUpCb.addItem("09.00");
            EtimeUpCb.addItem("09.30");
            EtimeUpCb.addItem("10.00");
            EtimeUpCb.addItem("10.30");
            EtimeUpCb.addItem("11.00");
            EtimeUpCb.addItem("11.30");
            EtimeUpCb.addItem("12.00");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }
       else if(StimeUpCb.getSelectedItem().equals("08.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("09.00");
            EtimeUpCb.addItem("09.30");
            EtimeUpCb.addItem("10.00");
            EtimeUpCb.addItem("10.30");
            EtimeUpCb.addItem("11.00");
            EtimeUpCb.addItem("11.30");
            EtimeUpCb.addItem("12.00");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("09.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("09.30");
            EtimeUpCb.addItem("10.00");
            EtimeUpCb.addItem("10.30");
            EtimeUpCb.addItem("11.00");
            EtimeUpCb.addItem("11.30");
            EtimeUpCb.addItem("12.00");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");   
            
         }else if(StimeUpCb.getSelectedItem().equals("09.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("10.00");
            EtimeUpCb.addItem("10.30");
            EtimeUpCb.addItem("11.00");
            EtimeUpCb.addItem("11.30");
            EtimeUpCb.addItem("12.00");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("10.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("10.30");
            EtimeUpCb.addItem("11.00");
            EtimeUpCb.addItem("11.30");
            EtimeUpCb.addItem("12.00");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("10.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("11.00");
            EtimeUpCb.addItem("11.30");
            EtimeUpCb.addItem("12.00");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("11.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("11.30");
            EtimeUpCb.addItem("12.00");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("11.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("12.00");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("12.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("12.30");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");   
            
         }else if(StimeUpCb.getSelectedItem().equals("12.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("13.00");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("13.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("13.30");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("13.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("14.00");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("14.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("14.30");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("14.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("15.00");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("15.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("15.30");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("15.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("16.00");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("16.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("16.30");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30"); 
            
         }else if(StimeUpCb.getSelectedItem().equals("16.30")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("17.00");
            EtimeUpCb.addItem("17.30");  
            
         }else if(StimeUpCb.getSelectedItem().equals("17.00")){
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
            EtimeUpCb.addItem("17.30");   
            
         }else{
             
            EtimeUpCb.removeAllItems();
            EtimeUpCb.addItem("Select");
         
         }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DateUpCB;
    private javax.swing.JComboBox<String> EtimeUpCb;
    private javax.swing.JComboBox<String> GrpUpCB;
    private javax.swing.JComboBox<String> SsIDUpCB;
    private javax.swing.JComboBox<String> StimeUpCb;
    private javax.swing.JComboBox<String> SubGrpUpCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> lnmUpCb;
    // End of variables declaration//GEN-END:variables
}
