/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagement;

import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Thiline Tissera
 */
public class Statistic extends javax.swing.JInternalFrame {

    /**
     * Creates new form Statistic
     */
    public Statistic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        regLec = new javax.swing.JRadioButton();
        regStud = new javax.swing.JRadioButton();
        regSub = new javax.swing.JRadioButton();
        regRoom = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        pie = new javax.swing.JButton();
        Histogram = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        buttonGroup1.add(regLec);
        regLec.setText("Registered lecturers");
        regLec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regLecActionPerformed(evt);
            }
        });

        buttonGroup1.add(regStud);
        regStud.setText("Registered Students");
        regStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regStudActionPerformed(evt);
            }
        });

        buttonGroup1.add(regSub);
        regSub.setText("Registered Subjects");

        buttonGroup1.add(regRoom);
        regRoom.setText("Registered Rooms");
        regRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRoomActionPerformed(evt);
            }
        });

        pie.setText("PIE CHART");
        pie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieActionPerformed(evt);
            }
        });

        Histogram.setText("Histogram");
        Histogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistogramActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regSub)
                            .addComponent(regRoom)
                            .addComponent(regStud)
                            .addComponent(regLec))
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(392, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Histogram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pie)
                        .addGap(122, 122, 122))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pie)
                    .addComponent(Histogram))
                .addGap(58, 58, 58)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regLec)
                        .addGap(28, 28, 28)
                        .addComponent(regStud)
                        .addGap(28, 28, 28)
                        .addComponent(regSub)
                        .addGap(27, 27, 27)
                        .addComponent(regRoom))
                    .addComponent(jScrollPane1))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regLecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regLecActionPerformed

    private void regStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regStudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regStudActionPerformed

    private void regRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regRoomActionPerformed

    private void pieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieActionPerformed
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("MALE", new Integer(321));
        pieDataset.setValue("FEMALE", new Integer(230));
        JFreeChart chart = ChartFactory.createPieChart("Gender", pieDataset, true, true, true);
        PiePlot p=(PiePlot)chart.getPlot();
//        p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Pie Chart", chart);
        frame.setVisible(true);
        frame.setSize(600,600);
    }//GEN-LAST:event_pieActionPerformed

    private void HistogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistogramActionPerformed

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(551, "Subjects", "MTIT");
        dataset.setValue(100, "Subjects", "ML");
        dataset.setValue(121, "Subjects", "Robotics");
        dataset.setValue(200, "Subjects", "SQA");
        dataset.setValue(551, "Subjects", "PPW");
        dataset.setValue(130, "Subjects", "ISA");
        
        JFreeChart chart = ChartFactory.createBarChart("Subjects", "Subjet Name", "Number of Students", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        ChartFrame frame = new ChartFrame("Bar Chart for Subjects", chart);
        frame.setVisible(true);
        frame.setSize(600,600);
        
    }//GEN-LAST:event_HistogramActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Histogram;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton pie;
    private javax.swing.JRadioButton regLec;
    private javax.swing.JRadioButton regRoom;
    private javax.swing.JRadioButton regStud;
    private javax.swing.JRadioButton regSub;
    // End of variables declaration//GEN-END:variables
}
