/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagement;

import java.sql.ResultSet;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import jdk.jshell.EvalException;

/**
 *
 * @author Thiline Tissera
 */
public class Subjects extends javax.swing.JInternalFrame {

    /**
     * Creates new form Subjects
     */
    public Subjects() {
        initComponents();
        LoadTable();
        
       this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI)this.getUI();
        bui.setNorthPane(null);
 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        subCode_tf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SubName_tf = new javax.swing.JTextField();
        Sem2 = new javax.swing.JRadioButton();
        Sem1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        offerdYr_cb = new javax.swing.JComboBox<>();
        tuteHours = new javax.swing.JSpinner();
        Lec_hours = new javax.swing.JSpinner();
        LabHours = new javax.swing.JSpinner();
        EvoHours = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        Add_btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();
        Clear_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Search_tf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Academic Year & Sem", "Programme", "Group No", "Group ID", "Sub Group No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Offered Year");

        jLabel2.setText("Subject Name");

        jLabel3.setText("Offered Semester");

        jLabel4.setText("Subject Code");

        SubName_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubName_tfActionPerformed(evt);
            }
        });

        buttonGroup5.add(Sem2);
        Sem2.setText("2nd Semester ");
        Sem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sem2ActionPerformed(evt);
            }
        });

        buttonGroup5.add(Sem1);
        Sem1.setText("1st Semester ");
        Sem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sem1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Number Of Lecturer Hours");

        jLabel6.setText("Number Of Tutorial Hours");

        jLabel7.setText("Number Of Lab Hours");

        jLabel8.setText("Number Of Evaluation Hours");

        offerdYr_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "1", "2", "3", "4" }));

        Add_btn.setText("Add");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        Update_btn.setText("Update");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        Delete_btn.setText("Delete");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        Clear_btn.setText("Clear");
        Clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Delete_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Update_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Sem1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Sem2))
                            .addComponent(offerdYr_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subCode_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SubName_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lec_hours, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(80, 80, 80)
                        .addComponent(LabHours, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tuteHours, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EvoHours, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(offerdYr_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sem1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubName_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subCode_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lec_hours, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tuteHours, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabHours, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EvoHours, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        Search_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_tfKeyReleased(evt);
            }
        });

        jLabel9.setText("Search");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Offered Year", "Offered Semester", "Subject Name", "Subject Code", "Lecure Hours", "Tute Hours", "Lab Hours", "Evaluation Hours"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Search_tf))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("Subjects Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String Sem = "";
    String PrimaryKey = "";
    
    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        
        //JOptionPane.showMessageDialog(null, "Sem : " +Sem);
        
        String OfferdYear =offerdYr_cb.getSelectedItem().toString();
        String SubName = SubName_tf.getText();
        String SubCode = subCode_tf.getText();
        String LecHours = Lec_hours.getValue().toString();
        String TuteHours = tuteHours.getValue().toString();
        String LabBours = LabHours.getValue().toString();       
        String EvloluationHours = EvoHours.getValue().toString();
                
        
       if(OfferdYear == "Select")
       {
                JOptionPane.showMessageDialog(null, "Please Select Offerd Year");
                
         }
       else
       {
           if(validateFields() && validateAdd()){
            try
            {
                DataBase.setData("insert into subjects(year,semester,subname,subcode,lecHours,tuteHours,labHours,EvalutionHours) values('"+OfferdYear+"','"+Sem+"','"+SubName+"','"+SubCode+"','"+LecHours+"','"+TuteHours+"','"+LabBours+"','"+EvloluationHours+"')");
                JOptionPane.showMessageDialog(null, "Subject Successfully Added");
                
                 Refresh();
                 Sem = "";

            }
            catch (Exception e)
            {
                        JOptionPane.showMessageDialog(null, "Failed" + e);
            }
           }
            
            LoadTable();
       }
    }//GEN-LAST:event_Add_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
       
        String OfferdYear =offerdYr_cb.getSelectedItem().toString();
        String SubName = SubName_tf.getText();
        String SubCode = subCode_tf.getText();
        String LecHours = Lec_hours.getValue().toString();
        String TuteHours = tuteHours.getValue().toString();
        String LabBours = LabHours.getValue().toString();       
        String EvloluationHours = EvoHours.getValue().toString();
        
        if(Sem1.isSelected()){
        
            Sem = "1";
        }else if(Sem2.isSelected()){
        
            Sem = "2";
        }
        
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int row = jTable2.getSelectedRow();

        if (row != -1) 
        {
            if(OfferdYear == "Select")
            {
                JOptionPane.showMessageDialog(null, "Select Offerd Year");
            }
            else
            {
                int confirm = JOptionPane.showConfirmDialog(null, "Do you want to Update?", "Update", JOptionPane.YES_NO_OPTION); 
                if (confirm == 0) 
                {
                    try
                    {
                        
                        if(validateFields()){
                        
                        DataBase.setData("UPDATE subjects set year = '"+OfferdYear+"', Semester = '"+Sem+"', subname = '"+SubName+"',subcode = '"+SubCode+"',lecHours = '"+LecHours+"',tuteHours = '"+TuteHours+"',labHours = '"+LabBours+"',EvalutionHours = '"+EvloluationHours+"' where ID = '"+PrimaryKey+"' ");
                        JOptionPane.showMessageDialog(null, " Successfully Updated");
                      
                         Refresh();
                        }
                    }
                    catch (Exception e)
                    {
                              JOptionPane.showMessageDialog(null, "Failed" + e);
                    }
               
                  LoadTable();
                }
            }
        }
        
        else 
        {
                JOptionPane.showMessageDialog(null, "Please Select a row for Update");
        }
     
    }//GEN-LAST:event_Update_btnActionPerformed

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int row = jTable2.getSelectedRow();
 
        if (row != -1) 
        {
        
            int confirm = JOptionPane.showConfirmDialog(null, "Do you want to delete?", "Delete", JOptionPane.YES_NO_OPTION); 
            if (confirm == 0) 
            {
                try
                {
                  DataBase.setData("DELETE FROM subjects WHERE id = '"+PrimaryKey+"'");
                  JOptionPane.showMessageDialog(null, "Successfully Deleted");

                }
                catch (Exception e)
                {
                          JOptionPane.showMessageDialog(null, "Failed" + e);
                }
              Refresh();
              LoadTable();
            }
        }
        else
        {
             JOptionPane.showMessageDialog(null, "Please Select a Row for Delete");
        }
        
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void Clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_btnActionPerformed
        //System.out.println("Primary Key :" + PrimaryKey);
        
        Refresh();
        LoadTable();
    }//GEN-LAST:event_Clear_btnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        
        String Lecs , Tute, Lab, Evo;
        
        PrimaryKey = (jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        offerdYr_cb.setSelectedItem(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        Sem2.setSelected("2".equalsIgnoreCase(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString())?true:false);
        Sem1.setSelected("1".equalsIgnoreCase(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString())?true:false);
        if(!("2".equalsIgnoreCase(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString()))&& 
                !("1".equalsIgnoreCase(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString()))){
            buttonGroup5.clearSelection();
        }
        SubName_tf.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        subCode_tf.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        
        
        Lecs = (jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString());
        Tute = (jTable2.getValueAt(jTable2.getSelectedRow(), 6).toString());
        Lab  = (jTable2.getValueAt(jTable2.getSelectedRow(), 7).toString());
        Evo = (jTable2.getValueAt(jTable2.getSelectedRow(), 8).toString());
             
        int Lecture = Integer.parseInt(Lecs);
        int Tutorial = Integer.parseInt(Tute);
        int Laborotary = Integer.parseInt(Lab);
        int Evolution = Integer.parseInt(Evo);
        
        Lec_hours.setValue(Lecture);
        tuteHours.setValue(Tutorial);
        LabHours.setValue(Laborotary);
        EvoHours.setValue(Evolution);
              
      
    }//GEN-LAST:event_jTable2MouseClicked

    private void Sem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sem2ActionPerformed
        Sem = "2";
    }//GEN-LAST:event_Sem2ActionPerformed

    private void Sem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sem1ActionPerformed
        Sem = "1";
    }//GEN-LAST:event_Sem1ActionPerformed

    private void Search_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_tfKeyReleased
        
        String search = Search_tf.getText();
        
       
            //String search =search_tf.getText();
            if (search.equalsIgnoreCase("")) 
            {
                LoadTable();
            } 
            else 
            {
                DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
                dtm.setRowCount(0);

                try 
                {

                        ResultSet rs = DataBase.getData("SELECT * FROM subjects WHERE year LIKE '%" + search + "%' "
                            + "OR semester LIKE '%"+search+"%' OR subName LIKE '%"+search+"%' OR subCode LIKE '%"+search+"%' OR lecHours LIKE '%"+search+"%' ");
                    while (rs.next()) 
                    {

                        Vector v = new Vector();

                        v.add(rs.getString(1));
                        v.add(rs.getString(2));  
                        v.add(rs.getString(3));  
                        v.add(rs.getString(4));
                        v.add(rs.getString(5));

                        v.add(rs.getString(6));  //lec hours
                        v.add(rs.getString(7));  // tute
                        v.add(rs.getString(8));
                        v.add(rs.getString(9));//lab

                        dtm.addRow(v);

                    }

                } 
                catch (Exception e)
                {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, e);
                }
            }
       
    }//GEN-LAST:event_Search_tfKeyReleased

    private void SubName_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubName_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubName_tfActionPerformed

     public void Refresh()
    {
        offerdYr_cb.setSelectedItem("Select");
        SubName_tf.setText("");
        subCode_tf.setText("");
        Lec_hours.setValue(0);
        tuteHours.setValue(0);
        LabHours.setValue(0);       
        EvoHours.setValue(0);
        buttonGroup5.clearSelection();
        Search_tf.setText("");
        Sem = "";
        
    }
  

    public void LoadTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        dtm.setRowCount(0);
        
        try{
              
                ResultSet rs = DataBase.getData("Select*  from subjects");
                
                while (rs.next())
                {

                    Vector v = new Vector();
                   
                   
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));  
                    v.add(rs.getString(3));  
                    v.add(rs.getString(4));
                    v.add(rs.getString(5));
                
                    v.add(rs.getString(6));  //lec hours
                    v.add(rs.getString(7));  // tute
                    v.add(rs.getString(8));
                    v.add(rs.getString(9));//lab
                    
                    
                   

                    dtm.addRow(v);

                }

            } catch (Exception e) 
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
            }
           
    }
    
     public boolean validateFields(){
        
        String slec = Lec_hours.getValue().toString();
        String stute = tuteHours.getValue().toString();
        String slab = LabHours.getValue().toString();
        String seva = EvoHours.getValue().toString();
        
        int lec = Integer.parseInt(slec);
        int tute = Integer.parseInt(stute);
        int lab = Integer.parseInt(slab);
        int eva  = Integer.parseInt(seva);
        
        String code = subCode_tf.getText();
        
        String vname = "[a-z A-Z]+\\.?";
       
        //validate name
        Pattern pname = Pattern.compile(vname, Pattern.CASE_INSENSITIVE);
        Matcher n = pname.matcher(SubName_tf.getText());
       
        if(Sem.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Enter Semester ");
            return false;       
        }
        
        if (SubName_tf.getText().equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, "Enter Subect Name ");
            return false;
            
        } else{
        
            if (n.matches()) 
            {
               
            } else 
            {
                JOptionPane.showMessageDialog(null, "Subject Name can only contain letters");
                return false;
            }
        
        
        }  
        if (code.equalsIgnoreCase("")){
            
            JOptionPane.showMessageDialog(null, "Enter Subject Code");
            return false; 
            
        }else if(code.length()!= 6){
                         
            JOptionPane.showMessageDialog(null, "Subject code should be 6 characters long");
            return false;
                       
        }else if (code.length() == 6)
            {
                
                  char firstl =  code.charAt(0);
                  char secondl = code.charAt(1);
                  char firstd = code.charAt(2);
                  char secondd = code.charAt(3);
                  char thirdd = code.charAt(4);
                  char fourthd = code.charAt(5);
                
               if (Character.isUpperCase(firstl) && Character.isUpperCase(secondl)) 
                {
                 
                } else
                {
                    JOptionPane.showMessageDialog(null, "Enter UpperCase letters for first two characters of Subject Code");
                    return false;
                }
                if (Character.isDigit(firstd) && Character.isDigit(secondd) && Character.isDigit(thirdd) && Character.isDigit(fourthd)){
                
                }else{
                
                     JOptionPane.showMessageDialog(null, "Enter digits for last four characters of Sublect Code");
                    return false;
                }
            }    
        if (lec < 0){
        
            JOptionPane.showMessageDialog(null, "Lecture Hours should not be a negative value");
            return false;
            
        }
        if (tute < 0){
        
            JOptionPane.showMessageDialog(null, "Tutorial Hours should not be a negative value");
            return false;
            
        }
        if (lab < 0){
        
            JOptionPane.showMessageDialog(null, "Lab Hours should not be a negative value");
            return false;
            
        }
        if (eva < 0){
        
            JOptionPane.showMessageDialog(null, "Evaluation Hours should not be a negative value");
            return false;
        }        
           
        return true;
    }
     
    public boolean validateAdd(){
        
        String code = subCode_tf.getText();
        String exist = "";
    
        try
          {
  
                ResultSet ex = DataBase.getData("SELECT `subcode` FROM `subjects` WHERE `subcode` = '" +code+ "' GROUP BY `subcode` HAVING COUNT(*) > '-1'");

                while (ex.next())
                {
                    exist = ex.getString("subcode");
                    
                }
            } 
        catch (Exception e) 
        {
                
            JOptionPane.showMessageDialog(null, "Failed" + e);
        }
        
        if (exist != ""){
            
            JOptionPane.showMessageDialog(null, "Subject already exists under given Subject Code");
            return false;
        }
    
        return true;
    }
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JButton Clear_btn;
    private javax.swing.JButton Delete_btn;
    private javax.swing.JSpinner EvoHours;
    private javax.swing.JSpinner LabHours;
    private javax.swing.JSpinner Lec_hours;
    private javax.swing.JTextField Search_tf;
    private javax.swing.JRadioButton Sem1;
    private javax.swing.JRadioButton Sem2;
    private javax.swing.JTextField SubName_tf;
    private javax.swing.JButton Update_btn;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> offerdYr_cb;
    private javax.swing.JTextField subCode_tf;
    private javax.swing.JSpinner tuteHours;
    // End of variables declaration//GEN-END:variables
}
